"""add_vehicle_document_compliance_columns

Revision ID: 13fef421ab01
Revises: 62cf051286b0
Create Date: 2026-07-28 19:07:08.004783

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13fef421ab01'
down_revision: Union[str, Sequence[str], None] = '62cf051286b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('chassis_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('engine_number', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('registration_date', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('insurance_expiry_date', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('fitness_expiry_date', sa.DateTime(), nullable=True))
    op.add_column('vehicles', sa.Column('puc_expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'puc_expiry_date')
    op.drop_column('vehicles', 'fitness_expiry_date')
    op.drop_column('vehicles', 'insurance_expiry_date')
    op.drop_column('vehicles', 'registration_date')
    op.drop_column('vehicles', 'engine_number')
    op.drop_column('vehicles', 'chassis_number')
    # ### end Alembic commands ###
