"""add_arrived_at_source_time_to_trips

Revision ID: 14c70117d793
Revises: 9e6e1e180f4a
Create Date: 2026-07-15 14:37:43.273818

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14c70117d793'
down_revision: Union[str, Sequence[str], None] = '9e6e1e180f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('arrived_at_source_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'arrived_at_source_time')
    # ### end Alembic commands ###
