"""fuel table added1

Revision ID: 26b934579d00
Revises: e3c2d75f72fe
Create Date: 2026-07-13 18:35:01.116746

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '26b934579d00'
down_revision: Union[str, Sequence[str], None] = 'e3c2d75f72fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'fuel_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('driver_id', sa.Integer(), nullable=False),
        sa.Column('liters_refueled', sa.Float(), nullable=False),
        sa.Column('cost', sa.Float(), nullable=False),
        sa.Column('odometer', sa.Float(), nullable=False),
        sa.Column('is_flagged_fraud', sa.Boolean(), nullable=False),
        sa.Column('fraud_reason', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['driver_id'], ['drivers.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_fuel_logs_id'),
        'fuel_logs',
        ['id'],
        unique=False
    )

    # Add vehicle_type as nullable first
    op.add_column(
        'drivers',
        sa.Column('vehicle_type', sa.String(), nullable=True)
    )

    # Give existing drivers a value
    op.execute(
        "UPDATE drivers "
        "SET vehicle_type = 'Unknown' "
        "WHERE vehicle_type IS NULL"
    )

    # Make vehicle_type NOT NULL
    op.alter_column(
        'drivers',
        'vehicle_type',
        nullable=False
    )

    # Add odometer_km as nullable first
    op.add_column(
        'drivers',
        sa.Column('odometer_km', sa.Float(), nullable=True)
    )

    # Give existing drivers a value
    op.execute(
        "UPDATE drivers "
        "SET odometer_km = 0.0 "
        "WHERE odometer_km IS NULL"
    )

    # Make odometer_km NOT NULL
    op.alter_column(
        'drivers',
        'odometer_km',
        nullable=False
    )

    op.add_column(
        'trips',
        sa.Column(
            'fuel_consumed_liters',
            sa.Float(),
            nullable=True
        )
    )

    op.add_column(
        'trips',
        sa.Column(
            'carbon_emissions_kg',
            sa.Float(),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'carbon_emissions_kg')
    op.drop_column('trips', 'fuel_consumed_liters')
    op.drop_column('drivers', 'odometer_km')
    op.drop_column('drivers', 'vehicle_type')
    op.drop_index(op.f('ix_fuel_logs_id'), table_name='fuel_logs')
    op.drop_table('fuel_logs')
    # ### end Alembic commands ###
