"""source company column added

Revision ID: 2b714bc5858e
Revises: e754f5083017
Create Date: 2026-07-03 13:14:41.800297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b714bc5858e'
down_revision: Union[str, Sequence[str], None] = 'e754f5083017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('source_company', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('destination_company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_company')
    op.drop_column('trips', 'source_company')
    # ### end Alembic commands ###
