"""added_driver_and_trip_gps_coordinates

Revision ID: 2dabad468549
Revises: e68dccef6ee8
Create Date: 2026-07-09 12:21:13.943818

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dabad468549"
down_revision: Union[str, Sequence[str], None] = "e68dccef6ee8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "driver_location_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_driver_location_history_driver_id"),
        "driver_location_history",
        ["driver_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_driver_location_history_id"),
        "driver_location_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_driver_location_history_trip_id"),
        "driver_location_history",
        ["trip_id"],
        unique=False,
    )
    op.add_column("drivers", sa.Column("current_latitude", sa.Float(), nullable=True))
    op.add_column("drivers", sa.Column("current_longitude", sa.Float(), nullable=True))
    op.add_column(
        "drivers", sa.Column("last_location_update", sa.DateTime(), nullable=True)
    )
    op.add_column("trips", sa.Column("source_latitude", sa.Float(), nullable=True))
    op.add_column("trips", sa.Column("source_longitude", sa.Float(), nullable=True))
    op.add_column("trips", sa.Column("destination_latitude", sa.Float(), nullable=True))
    op.add_column(
        "trips", sa.Column("destination_longitude", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "destination_longitude")
    op.drop_column("trips", "destination_latitude")
    op.drop_column("trips", "source_longitude")
    op.drop_column("trips", "source_latitude")
    op.drop_column("drivers", "last_location_update")
    op.drop_column("drivers", "current_longitude")
    op.drop_column("drivers", "current_latitude")
    op.drop_index(
        op.f("ix_driver_location_history_trip_id"), table_name="driver_location_history"
    )
    op.drop_index(
        op.f("ix_driver_location_history_id"), table_name="driver_location_history"
    )
    op.drop_index(
        op.f("ix_driver_location_history_driver_id"),
        table_name="driver_location_history",
    )
    op.drop_table("driver_location_history")
    # ### end Alembic commands ###
