"""add_trip_id_to_fuel_log

Revision ID: 4afd5130cab0
Revises: 67af90106d1d
Create Date: 2026-07-14 19:09:05.044702

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4afd5130cab0'
down_revision: Union[str, Sequence[str], None] = '67af90106d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_logs', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fuel_logs', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_logs', type_='foreignkey')
    op.drop_column('fuel_logs', 'trip_id')
    # ### end Alembic commands ###
