"""add_cargo_columns

Revision ID: 5dcb7ef38d63
Revises: c4f99e36c140
Create Date: 2026-07-17 13:02:48.838355

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5dcb7ef38d63'
down_revision: Union[str, Sequence[str], None] = 'c4f99e36c140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_logs', sa.Column('audit_status', sa.String(), nullable=False, server_default='passed'))
    op.add_column('trips', sa.Column('cargo_weight_kg', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('cargo_volume_m3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'cargo_volume_m3')
    op.drop_column('trips', 'cargo_weight_kg')
    op.drop_column('fuel_logs', 'audit_status')
    # ### end Alembic commands ###
