"""add_geofence_radii_and_arrival_time

Revision ID: 62cf051286b0
Revises: 0ab5288da2cb
Create Date: 2026-07-28 18:24:35.702346

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62cf051286b0'
down_revision: Union[str, Sequence[str], None] = '0ab5288da2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('arrived_at_destination_time', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('geofence_origin_radius_m', sa.Float(), nullable=False, server_default='500.0'))
    op.add_column('trips', sa.Column('geofence_dest_radius_m', sa.Float(), nullable=False, server_default='500.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'geofence_dest_radius_m')
    op.drop_column('trips', 'geofence_origin_radius_m')
    op.drop_column('trips', 'arrived_at_destination_time')
    # ### end Alembic commands ###
