"""add vehicle_id to trips

Revision ID: 67af90106d1d
Revises: 126539147f0a
Create Date: 2026-07-14 11:46:55.010012

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67af90106d1d'
down_revision: Union[str, Sequence[str], None] = '126539147f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'vehicle_id')
    # ### end Alembic commands ###
