"""add_audit_and_payout_to_trips

Revision ID: 6bcc3ee0962e
Revises: 4afd5130cab0
Create Date: 2026-07-15 11:57:26.366715

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6bcc3ee0962e'
down_revision: Union[str, Sequence[str], None] = '4afd5130cab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('trips', sa.Column('gps_distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('odo_distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('audit_status', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('payout_status', sa.String(), nullable=True))
    
    # Update default values for existing rows
    op.execute("UPDATE trips SET audit_status = 'passed' WHERE audit_status IS NULL")
    op.execute("UPDATE trips SET payout_status = 'pending' WHERE payout_status IS NULL")
    
    # Alter column to nullable=False
    op.alter_column('trips', 'audit_status', nullable=False)
    op.alter_column('trips', 'payout_status', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'payout_status')
    op.drop_column('trips', 'audit_status')
    op.drop_column('trips', 'odo_distance_km')
    op.drop_column('trips', 'gps_distance_km')
    # ### end Alembic commands ###
