"""add vehicle fasttag balance

Revision ID: 6c50955c36d1
Revises: 7466270be9df
Create Date: 2026-07-23 16:35:22.288513

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c50955c36d1'
down_revision: Union[str, Sequence[str], None] = '7466270be9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fasttag_balance', sa.Float(), server_default='1000.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'fasttag_balance')
    # ### end Alembic commands ###
