"""add fuel theft alerts table

Revision ID: 7466270be9df
Revises: f8920101
Create Date: 2026-07-23 15:55:08.769090

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7466270be9df'
down_revision: Union[str, Sequence[str], None] = 'f8920101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proof_of_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_signature', sa.String(), nullable=True),
    sa.Column('delivery_notes', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('geofence_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_index(op.f('ix_proof_of_deliveries_id'), 'proof_of_deliveries', ['id'], unique=False)
    op.create_table('fuel_theft_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fuel_log_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('detected_loss_liters', sa.Float(), nullable=False),
    sa.Column('estimated_financial_loss', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['fuel_log_id'], ['fuel_logs.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_theft_alerts_id'), 'fuel_theft_alerts', ['id'], unique=False)
    op.drop_index(op.f('ix_trip_expenses_driver_id'), table_name='trip_expenses')
    op.drop_index(op.f('ix_trip_expenses_trip_id'), table_name='trip_expenses')
    op.drop_constraint(op.f('trip_expenses_trip_id_fkey'), 'trip_expenses', type_='foreignkey')
    op.drop_constraint(op.f('trip_expenses_driver_id_fkey'), 'trip_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'trip_expenses', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'trip_expenses', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_expenses', type_='foreignkey')
    op.drop_constraint(None, 'trip_expenses', type_='foreignkey')
    op.create_foreign_key(op.f('trip_expenses_driver_id_fkey'), 'trip_expenses', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('trip_expenses_trip_id_fkey'), 'trip_expenses', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_trip_expenses_trip_id'), 'trip_expenses', ['trip_id'], unique=False)
    op.create_index(op.f('ix_trip_expenses_driver_id'), 'trip_expenses', ['driver_id'], unique=False)
    op.drop_index(op.f('ix_fuel_theft_alerts_id'), table_name='fuel_theft_alerts')
    op.drop_table('fuel_theft_alerts')
    op.drop_index(op.f('ix_proof_of_deliveries_id'), table_name='proof_of_deliveries')
    op.drop_table('proof_of_deliveries')
    # ### end Alembic commands ###
