"""add_proof_of_delivery_table

Revision ID: 8bbd69c04286
Revises: a7d15aedf4a6
Create Date: 2026-07-29 18:34:23.844670

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8bbd69c04286'
down_revision: Union[str, Sequence[str], None] = 'a7d15aedf4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proof_of_deliveries', sa.Column('driver_id', sa.Integer(), nullable=False))
    op.add_column('proof_of_deliveries', sa.Column('recipient_phone', sa.String(), nullable=True))
    op.add_column('proof_of_deliveries', sa.Column('signature_data', sa.Text(), nullable=False))
    op.add_column('proof_of_deliveries', sa.Column('delivery_photo_url', sa.String(), nullable=True))
    op.add_column('proof_of_deliveries', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('proof_of_deliveries', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('proof_of_deliveries', sa.Column('verification_status', sa.String(), nullable=False))
    op.alter_column('proof_of_deliveries', 'delivery_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('proof_of_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('proof_of_deliveries_trip_id_key'), 'proof_of_deliveries', type_='unique')
    op.create_index(op.f('ix_proof_of_deliveries_trip_id'), 'proof_of_deliveries', ['trip_id'], unique=True)
    op.create_foreign_key(None, 'proof_of_deliveries', 'drivers', ['driver_id'], ['id'])
    op.drop_column('proof_of_deliveries', 'recipient_signature')
    op.drop_column('proof_of_deliveries', 'geofence_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proof_of_deliveries', sa.Column('geofence_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('proof_of_deliveries', sa.Column('recipient_signature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'proof_of_deliveries', type_='foreignkey')
    op.drop_index(op.f('ix_proof_of_deliveries_trip_id'), table_name='proof_of_deliveries')
    op.create_unique_constraint(op.f('proof_of_deliveries_trip_id_key'), 'proof_of_deliveries', ['trip_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('proof_of_deliveries', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('proof_of_deliveries', 'delivery_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('proof_of_deliveries', 'verification_status')
    op.drop_column('proof_of_deliveries', 'longitude')
    op.drop_column('proof_of_deliveries', 'latitude')
    op.drop_column('proof_of_deliveries', 'delivery_photo_url')
    op.drop_column('proof_of_deliveries', 'signature_data')
    op.drop_column('proof_of_deliveries', 'recipient_phone')
    op.drop_column('proof_of_deliveries', 'driver_id')
    # ### end Alembic commands ###
