"""all table updated

Revision ID: 9d3ecec34cee
Revises: 8a1b2c3d4e5f
Create Date: 2026-06-30 18:49:23.716497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d3ecec34cee'
down_revision: Union[str, Sequence[str], None] = '8a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('estimated_fare', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('cancel_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'cancel_reason')
    op.drop_column('trips', 'estimated_fare')
    op.drop_column('trips', 'duration_minutes')
    op.drop_column('trips', 'distance_km')
    # ### end Alembic commands ###
