"""add_start_end_odo_to_trips

Revision ID: 9e6e1e180f4a
Revises: 6bcc3ee0962e
Create Date: 2026-07-15 11:59:29.215319

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e6e1e180f4a'
down_revision: Union[str, Sequence[str], None] = '6bcc3ee0962e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('start_odometer', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('end_odometer', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'end_odometer')
    op.drop_column('trips', 'start_odometer')
    # ### end Alembic commands ###
