"""normalize_driver_and_vehicle_schemas

Revision ID: a7d15aedf4a6
Revises: 13fef421ab01
Create Date: 2026-07-29 13:22:35.065675

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7d15aedf4a6'
down_revision: Union[str, Sequence[str], None] = '13fef421ab01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('licensed_vehicle_class', sa.String(), nullable=False, server_default='HMV'))
    op.create_unique_constraint('uq_drivers_user_id', 'drivers', ['user_id'])
    op.create_unique_constraint('uq_drivers_license_number', 'drivers', ['license_number'])
    op.drop_column('drivers', 'vehicle_type')
    op.drop_column('drivers', 'odometer_km')
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=False, server_default='cargo_truck'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'vehicle_type')
    op.add_column('drivers', sa.Column('odometer_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'licensed_vehicle_class')
    # ### end Alembic commands ###
