"""add_downtime_and_personal_fuel

Revision ID: c4f99e36c140
Revises: c4feb9ade921
Create Date: 2026-07-16 17:06:09.228469

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4f99e36c140'
down_revision: Union[str, Sequence[str], None] = 'c4feb9ade921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_logs', sa.Column('is_personal_two_wheeler', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('maintenance_logs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_logs', 'completed_at')
    op.drop_column('fuel_logs', 'is_personal_two_wheeler')
    # ### end Alembic commands ###
