"""add pre trip safety inspections table

Revision ID: c4feb9ade921
Revises: 14c70117d793
Create Date: 2026-07-16 16:09:20.557809

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4feb9ade921'
down_revision: Union[str, Sequence[str], None] = '14c70117d793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_trip_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('brakes_passed', sa.Boolean(), nullable=False),
    sa.Column('tires_passed', sa.Boolean(), nullable=False),
    sa.Column('lights_passed', sa.Boolean(), nullable=False),
    sa.Column('steering_passed', sa.Boolean(), nullable=False),
    sa.Column('fluids_passed', sa.Boolean(), nullable=False),
    sa.Column('is_safe', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_index(op.f('ix_pre_trip_inspections_id'), 'pre_trip_inspections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_trip_inspections_id'), table_name='pre_trip_inspections')
    op.drop_table('pre_trip_inspections')
    # ### end Alembic commands ###
