"""add_driver_salary_and_payments

Revision ID: e3c2d75f72fe
Revises: 2dabad468549
Create Date: 2026-07-09 16:44:51.122355

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3c2d75f72fe'
down_revision: Union[str, Sequence[str], None] = '2dabad468549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('base_salary_paid', sa.Float(), nullable=False),
    sa.Column('commission_paid', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'year', 'month', name='uq_driver_payment_month_year')
    )
    op.create_index(op.f('ix_driver_payments_driver_id'), 'driver_payments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_payments_id'), 'driver_payments', ['id'], unique=False)
    op.add_column('drivers', sa.Column('base_salary', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('drivers', sa.Column('commission_percentage', sa.Float(), nullable=False, server_default='100.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'commission_percentage')
    op.drop_column('drivers', 'base_salary')
    op.drop_index(op.f('ix_driver_payments_id'), table_name='driver_payments')
    op.drop_index(op.f('ix_driver_payments_driver_id'), table_name='driver_payments')
    op.drop_table('driver_payments')
    # ### end Alembic commands ###
