"""priority column added in trip table

Revision ID: e68dccef6ee8
Revises: c2a1255fb3cc
Create Date: 2026-07-07 18:10:23.586348

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e68dccef6ee8'
down_revision: Union[str, Sequence[str], None] = 'c2a1255fb3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_availability_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_availability_history_driver_id'), 'driver_availability_history', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_availability_history_id'), 'driver_availability_history', ['id'], unique=False)
    op.create_table('trip_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_history_id'), 'trip_history', ['id'], unique=False)
    op.create_index(op.f('ix_trip_history_trip_id'), 'trip_history', ['trip_id'], unique=False)
    op.add_column('trips', sa.Column('priority', sa.String(), nullable=False, server_default='normal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'priority')
    op.drop_index(op.f('ix_trip_history_trip_id'), table_name='trip_history')
    op.drop_index(op.f('ix_trip_history_id'), table_name='trip_history')
    op.drop_table('trip_history')
    op.drop_index(op.f('ix_driver_availability_history_id'), table_name='driver_availability_history')
    op.drop_index(op.f('ix_driver_availability_history_driver_id'), table_name='driver_availability_history')
    op.drop_table('driver_availability_history')
    # ### end Alembic commands ###
