""" driver table updated foreign key updated12

Revision ID: e754f5083017
Revises: a34cad05fa3b
Create Date: 2026-07-02 15:57:34.407827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e754f5083017'
down_revision: Union[str, Sequence[str], None] = 'a34cad05fa3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'user_id')
    # ### end Alembic commands ###
