""" driver table updated

Revision ID: f4be0d863f62
Revises: 9d3ecec34cee
Create Date: 2026-07-02 15:09:32.187376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4be0d863f62'
down_revision: Union[str, Sequence[str], None] = '9d3ecec34cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable OR with default
    op.add_column(
        'trips',
        sa.Column('is_regular', sa.Boolean(), nullable=True)
    )

    op.add_column(
        'trips',
        sa.Column('scheduled_date', sa.DateTime(), nullable=True)
    )

    # Step 2: Backfill existing data
    op.execute("UPDATE trips SET is_regular = false WHERE is_regular IS NULL")

    # Step 3: Make column NOT NULL
    op.alter_column('trips', 'is_regular', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'scheduled_date')
    op.drop_column('trips', 'is_regular')
    # ### end Alembic commands ###
